name: Deployment workflow
  
on:
  push: 
    branches: 
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl https://get.okteto.com -sSfL | sh
          okteto context use https://cloud.okteto.com --token ${{ secrets.OKTETO_TOKEN }}
          
          echo "${{ secrets.ENV_FILE }}" > .env

          okteto deploy --build --namespace=${{secrets.OKTETO_ZEUS_NAMESPACE }} 